FROM golang:1.15 as build

RUN apt-get update && apt-get install -y ninja-build

WORKDIR /go/src
RUN git clone https://github.com/pavlovskyive/kpi-lab-1
WORKDIR /go/src/kpi-lab-1
RUN go get -u ./build/cmd/bood

WORKDIR /go/src/kpi-lab-2
COPY . .

# TODO: Замініть на запуск bood, який призводить до виконання інтеграційних тестів.
ENTRYPOINT ["bood", "out/bin/integration"]
